### ISSUE TITLE
How to SSR with latest Meteor?

### ISSUE THREAD

**Issue by Anonyfox** [Meteor-Community-Packages/react-router-ssr#12]
I am using a fresh meteor app (meteor version 2.2, `meteor create dummy --typescript`) and literally have no clue what steps are neccessary to make things work. I have looked at #5 and got a few hints... but the following seems broken: 

### importing

`import { renderWithSSR } from "meteor/communitypackages:react-router-ssr";` => `Cannot find module 'meteor/communitypackages:react-router-ssr' or its corresponding type declarations`

but it seems that the code _does_ run, only my vscode reports some error?

### building

```sh
W20210625-15:22:32.256(2)? (STDERR) WARNING: npm peer requirements (for communitypackages:react-router-ssr) not installed:
W20210625-15:22:32.299(2)? (STDERR)    - react-router-dom@4.x || 5.x not installed.
W20210625-15:22:32.299(2)? (STDERR) 
W20210625-15:22:32.299(2)? (STDERR)   Read more about installing npm peer dependencies:
W20210625-15:22:32.299(2)? (STDERR)     http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20210625-15:22:32.299(2)? (STDERR)   
=> Started your app.
```

but i have 

```json
{
    "react": "^16.13.1",
    "react-bootstrap": "^1.6.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^6.1.0",
    "react-router-bootstrap": "^0.25.0",
    "react-router-dom": "^5.2.0"
}
```
in my package.json

### using

after copying the initial `client/main.tsx` to `imports/main.tsx` and then changing the content of `client/main.tsx` to `import '../imports/main'` things seem to work, but then I see in the browser a warning: 

```
Warning: Expected server HTML to contain a matching <div> in <div>.
    in div (created by Container)
    in Container (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in App
    in Switch (created by ReactRouterSSR)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by ReactRouterSSR)
    in ReactRouterSSR
```

So, it looks like it _does_ work when running client-side, but something is off with the initial HTML. With using cURL to check the initial HTML there is indeed no rendered body within the HTML at all, just the `<div id="react-target"></div>` and some script tags.

Is there _anything_ I have to do to make the server _actually_ perform SSR?

**Comment by copleykj** [comment]
> import { renderWithSSR } from "meteor/communitypackages:react-router-ssr"; => Cannot find module 'meteor/communitypackages:react-router-ssr' or its corresponding type declarations

This is a typescript error stating that it can't find the type definitions for the module. Currently none exist so you can either write them, or just squelch the error by defining a blank module definition locally in your project.

```sh
W20210625-15:22:32.256(2)? (STDERR) WARNING: npm peer requirements (for communitypackages:react-router-ssr) not installed:
W20210625-15:22:32.299(2)? (STDERR)    - react-router-dom@4.x || 5.x not installed.
W20210625-15:22:32.299(2)? (STDERR) 
W20210625-15:22:32.299(2)? (STDERR)   Read more about installing npm peer dependencies:
W20210625-15:22:32.299(2)? (STDERR)     http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20210625-15:22:32.299(2)? (STDERR)   
=> Started your app.
```

This warning would be displayed if react-router-dom isn't imported. This is because Meteor's build system statically analyzes imports and doesn't include the modules in the build that are not imported.

> after copying the initial client/main.tsx to imports/main.tsx and then changing the content of client/main.tsx to import '../imports/main' things seem to work, but then I see in the browser a warning:

You mention here that you import `../imports/main` on the client, but there is no mention of a server import. If you have not imported this anywhere in the server, then this is likely the issue and would also explain the peer dependency warning in the server console.

Hopefully this helps to get everything sorted out. Let me know if you need any further help.

**Comment by Anonyfox** [comment]
Thanks for the explanations! So, could you guide me a little further and describe what _exactly_ is needed on the last part? I scaffold `meteor create dummy --typescript`, and there was no obvious part where to put the "server" part of SSR. There is only a server file with some startup code that inserts ToDo-items if there are none.

**Comment by copleykj** [comment]
Sure! The server part will be no different than the client part. You already have `../imports/main` imported at `/client/main.tsx` now you just need to import the same at `/server/main.js`

**Comment by Anonyfox** [comment]
Thanks, just importing the file on server.tsx did indeed work, I just needed to ensure to use BrowserRouter or StaticRouter dependent on `Meteor.isClient`. 

But: it seems that always the index route `"/"` gets rendered on the server even when I load some specific URL (like `"/subsite"`, confirmed with cURL), and then the client takes over and renders the actually correct site. Seems that I am _still_ missing something?

**Comment by copleykj** [comment]
You'll just need to remove the router components since these are handled by the package.

**Comment by Anonyfox** [comment]
Finally!

changed my `imports/ui/App.tsx` to:

```typescript
import React from 'react';
import { NavBar } from './components/NavBar';
import { Routes } from './components/Routes';

export const App = () => {
  return (
    <>
      <NavBar />
      <Routes />
    </>
  )
}
```

and things work! thank you so much!

One minor nitpick: I had to move `import 'rsuite/dist/styles/rsuite-dark.css';` from `imports/ui/App.tsx` to `client/main.tsx` because the raw CSS file made the renderer break. Is this intentional or some bug? Just asking, because having CSS included initially would reduce the "flickering" significantly

**Comment by copleykj** [comment]
When using SSR its best not to import styles into your javascript files. When importing them into js code, the styles are not added to the page css, they are dynamically added to a style tag in the head at runtime and can lead to issues with FOUC when page content loads before the css is added and parsed. Instead, import them into the main css file using the @import syntax. 

I'm assuming from your import, the css is coming from an npm module, If not you'll need to adjust the import accordingly.

In your main css file you should be able to add something like the following:

```css
@import '{}/node_modules/rsuite/dist/styles/rsuite-dark.css';
```

**Comment by Anonyfox** [comment]
It seems that importing raw css directly from node_modules does not work currently (the dev server tries to serve an un-bundled css file from the localhost:3000/node_modules path, which seems to not exist in the app). But "ordinary" CSS within my app works so far, so I copied the external css into the `/public` folder and load it before my own CSS. 

Works good enough for now, nothing flickers, and I don't have many such external CSS includes (yet). Anyway, seems like a different topic not related to this package.

Thanks again @copleykj - maybe someone else with the same problems can look at the example files I posted above to get things working, too! 

A heads up for you: I used meteor heavily for products in the past (when there was mostly blaze/coffeescript/less) and the "SSR solution" was to spin up some phantomJS processes via package... a horrible hack that made my hardware costs explode for content-heavy sites, leading me to abandon meteor completely. Now there is React, with a clean SSR/rehydration story, and things work as they should be after all these years... making me reconsider using meteor again, especially thanks to this package!

**Comment by make-github-pseudonymous-again** [comment]
> Here is my `imports/main.tsx`:
> 
> ```ts
> import React from 'react';
> import { Meteor } from 'meteor/meteor';
> // import { render } from 'react-dom';
> import { renderWithSSR } from "meteor/communitypackages:react-router-ssr";
> import { App } from '/imports/ui/App'
> 
> Meteor.startup(() => {
>   renderWithSSR(<App />);
> });
> ```

Is `Meteor.startup(...)` wrapping required?
