### ISSUE TITLE
Please Update React Router Dom To 6.x

### ISSUE THREAD

**Issue by Saeeed-B** [Meteor-Community-Packages/react-router-ssr#16]
Please Update React Router Dom To 6.x.

**Comment by Saeeed-B** [comment]
![image](https://user-images.githubusercontent.com/36485982/151664409-0c0fc827-e57a-423a-bb62-50623e30e5ad.png)

**Comment by Saeeed-B** [comment]
@copleykj 
I do not think you need many changes for this update.

I just saw this item for this update for this package:

[get-staticrouter-from-react-router-domserver](https://reactrouter.com/docs/en/v6/upgrading/v5#get-staticrouter-from-react-router-domserver)

For general information, please refer to:
[https://reactrouter.com/docs/en/v6/upgrading/v5](https://reactrouter.com/docs/en/v6/upgrading/v5)

**Comment by Saeeed-B** [comment]
Is anyone here?

**Comment by copleykj** [comment]
PRs welcome.

**Comment by fangjj** [comment]
[PRs](https://github.com/Meteor-Community-Packages/react-router-ssr/pull/24)
