### ISSUE TITLE
Invalid DOM property `referrerpolicy`. Did you mean `referrerPolicy`?

### ISSUE THREAD

**Issue by Saeeed-B** [Meteor-Community-Packages/react-router-ssr#17]
![image](https://user-images.githubusercontent.com/36485982/151713976-892e827d-b0ac-43e4-bd36-bbf5e252ec63.png)

**Comment by StorytellerCZ** [comment]
@Saeeed-B what does the code that throws this error look like?

**Comment by copleykj** [comment]
This looks project specific and potentially unrelated. Closing for now. Feel free to provide a minimal reproduction.
