### ISSUE TITLE
error caught on publication:

### ISSUE THREAD

**Issue by Saeeed-B** [Meteor-Community-Packages/react-router-ssr#18]
![image](https://user-images.githubusercontent.com/36485982/154227894-6d31462c-8300-45fe-b162-befb22c4397a.png)

**Comment by StorytellerCZ** [comment]
@Saeeed-B we need a bit more information than this. Reproduction is best, second best is adding description of what are you trying to achive, what you expect to happen and then what is actually happening.

**Comment by StorytellerCZ** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.

**Comment by Saeeed-B** [comment]
this is from  line 188 of publish_context.js

**Comment by Saeeed-B** [comment]
@StorytellerCZ @coagmano 
from this line :

[https://github.com/Meteor-Community-Packages/meteor-fast-render/blob/0a3e50c69e276ab7e2c988c113a2e5fa3a1df002/lib/server/publish_context.js#L118](https://github.com/Meteor-Community-Packages/meteor-fast-render/blob/0a3e50c69e276ab7e2c988c113a2e5fa3a1df002/lib/server/publish_context.js#L118)

**Comment by Saeeed-B** [comment]
What exactly is this error for?
Maybe I can find the problem better
