### ISSUE TITLE
Readme can be easier maybe?

### ISSUE THREAD

**Issue by lucfranken** [Meteor-Community-Packages/react-router-ssr#5]
While testing out this package with quite standard Meteor app with React and useTracker I noticed the implementation is actually easier than it seems from the readme. My steps:

0. Install packages as described in existing readme.
1. Move existing client/main.js -> imports/main.js
2. In imports/main.js replace render( with renderWithSSR(renderRoutes());
3. Client/main.js becomes: import '../imports/main';
4. In server/main.js add import '../imports/main';
5. Replace history with: const customHistory = Meteor.isClient ? createBrowserHistory() : createMemoryHistory();

Done. It actually works and incredibly speeds up the page load.

What I was surprised about was the fact that the element to render to has a hardcoded classname: react-app while the signature of the React method is:

````js
render(renderRoutes(), document.getElementById('react-target'));
````

Are those things which might be interesting to change or is there a different vision for this package?

**Comment by nilooy** [comment]
i have tried this package couple of times, it's working without any issue but there's no ssr so far as the page source is empty

**Comment by OlivierJM** [comment]
Thanks a lot @lucfranken, it actually wasn't clear for me in the readme on where to keep the files and restructure.

**Comment by copleykj** [comment]
All of these are great points.. I'll be bringing this package up to date to the latest version of react and react-router soon and at that time I'll incorporate some of this as well.

**Comment by OlivierJM** [comment]
Thanks @copleykj
